### PR TITLE
Fixes for compiler warnings and also use nanosleep instead of obsolete usleep function

### PR DESCRIPTION
**Pull request by cranderson**
It is mandatory to fix compiler warnings on on Feodra which uses -Werror in the default CFLAGS.  Here are a bunch of fixes to allow msed to be built as a package on Fedora.  Additionally, there is one commit that changes the use of the obsolete usleep function to nanosleep.

### CODE REVIEW

**Comment by r0m30** [comment]
What compiler does Fedora use, looking at the makefiles in nbproject I see -Werror being used.

**Comment by cranderson** [comment]
Here is an example build log (with the patches applied):

https://kojipkgs.fedoraproject.org//work/tasks/8654/10488654/build.log

It shows them using "redhat-hardened-cc1" but even without the hardened config, it still fails without the patches.

g++ -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic   -c -O2 -Werror -s -Imsed/linux -Imsed -std=c++11 -MMD -MP -MF "build/Release_x86_64/GNU-Linux-x86/msed/MsedCommand.o.d" -o build/Release_x86_64/GNU-Linux-x86/msed/MsedCommand.o msed/MsedCommand.cpp

**Comment by r0m30** [comment]
@cranderson   msed is now Drive-Trust-Alliance/sedutil. I've added -Wall to the nbproject files and fixed all the warnings in that repo.  Is there a reason, other that it is deprecated, why you replaced usleep?  Does the Fedora compiler flag deprecated functions?

Thanks for the pointer to makeroot, I tried another root builder and it ended up larger than tinycore.  

BTW the bug loading large PBAs on Crucial drives is also fixed (at least for up to  100mb PBAs and if you have a PBA that large no one is going ever load it.)

**Comment by cranderson** [comment]
The usleep change wasn't strictly for Fedora.  I am using msed with uClibc, which doesn't have usleep (I think it might if I turn on support for an obsolete C standard), so I replaced it with nanosleep which is implemented in uClibc by default.

**Comment by r0m30** [comment]
OK, that makes sense, I worked around it by telling makeroot to use glibc.  Will that work for you?  the new Linux based PBA's are 3MB and built using makeroot.  The rescue system is still TinyCore but that could change in the future. 

 Thanks again for the pointer to makeroot!

**Comment by r0m30** [comment]
The makefiles have been updated and the compile errors are fixed in the Drive-Trust-Alliance/sedutil repo.  If you have any more problems please open issues/pull requests in that repo.

**Pull request closed without merging**
