### PR TITLE
Suggested guidance from a newbie on building for windows.

### PR DESCRIPTION
**Pull request by brendanhoar**
Mike,

Hopefully this readme will help others building MSED on windows 8.x machines. Feel free to modify or discard.

I'm starting to take a look at the code with an eye towards adding support for talking to SEDs via UASP (USB Attached SCSI Protocol) under Windows 8 (which allows ATA tunneling to some USB 3.x devices) in my not very copious at all free time. :)

### CODE REVIEW

**Comment by r0m30** [comment]
Thanks Brendan,

I use AllSigned as my PowerShell execution policy, is that not available in Win 8.1?

I'll add this and update the build instructions on the web site as well.

**Comment by brendanhoar** [comment]
Mike,

I believe AllSigned is also valid, I'll check to see if that works in my
environment when I get back to the personal development machine tonight.

By default, under 8.x, both policies are set to Restricted, I believe.

**Comment by brendanhoar** [comment]
I ended up having to work at home this morning, so I took a look with my early lunch and updated the readme based on our conversation and testing.

**Comment by brendanhoar** [comment]
To clarify: I think AllSigned will work for you because you have the certificate chain installed that matches the signature on the script. AllSigned won't work for anyone else unless they re-sign the script with their own certificate that is supported by a locally installed certificate chain (or perhaps import your cert?). Hence my recommendation to use RemoteSigned (essentially "Unrestricted" for all scripts that aren't marked by IE as downloaded from the internet) to get it compile is a stop gap. As a semi-infosec guy, I don't like that configuration as a long term solution, so the file contains additional comments indicating the user should investigate signing the script themselves and adjusting the powershell security policy to a more secure setting.

**Comment by r0m30** [comment]
Yes, AllSigned works because I have a self signed cert and a my root cert is installed in the local certificate store,  I was asking so the option of signing the script could be added to the text (which you did) because as you pointed out that is the most secure (or least insecure) option available.  

I'll add this when I get back to the code.

PS if you are looking at the code and hit a WTF was he thinking spot.  Send me an email and I'll try and explain my insanity.

**Pull request merged**
